name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 6432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    env:
      DB_HOST_TEST: localhost
      DB_PORT_TEST: 6432
      DB_NAME_TEST: postgres
      DB_USER_TEST: postgres
      DB_PASS_TEST: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/backend/src:$(pwd)/backend/test_backend" >> $GITHUB_ENV

    - name: Set DATABASE_URL environment variable
      run: |
        echo "DATABASE_URL=postgres://${{ env.DB_USER_TEST }}:${{ env.DB_PASS_TEST }}@${{ env.DB_HOST_TEST }}:${{ env.DB_PORT_TEST }}/${{ env.DB_NAME_TEST }}" >> $GITHUB_ENV

    - name: Debug ENV variables
      run: printenv

    - name: Run tests
      run: |
        export DATABASE_URL="postgres://${{ env.DB_USER_TEST }}:${{ env.DB_PASS_TEST }}@${{ env.DB_HOST_TEST }}:${{ env.DB_PORT_TEST }}/${{ env.DB_NAME_TEST }}"
        pytest
