name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 6432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy .env to GITHUB_ENV
      run: |
        cat .env >> $GITHUB_ENV

    - name: Set DATABASE_URL environment variable
      run: |
        echo "DATABASE_URL=postgres://$DB_USER_TEST:$DB_PASS_TEST@$DB_HOST_TEST:$DB_PORT_TEST/$DB_NAME_TEST" >> $GITHUB_ENV

    - name: Run tests
      run: |
        export DATABASE_URL="postgres://$DB_USER_TEST:$DB_PASS_TEST@$DB_HOST_TEST:$DB_PORT_TEST/$DB_NAME_TEST"
        pytest
