name: backend_test CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run backend tests
        working-directory: ./backend
        run:  |
          docker run --name test_track -p 7432:5432 -e POSTGRES_PASSWORD=postgres -d postgres:latest
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest