name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 6432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    env:
      DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
      DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
      DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
      DB_PASS_TEST: ${{ secrets.DB_PASS_TEST }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set DATABASE_URL environment variable
      run: |
        echo "DATABASE_URL=postgres://${{ secrets.DB_USER_TEST }}:${{ secrets.DB_PASS_TEST }}@${{ secrets.DB_HOST_TEST }}:${{ secrets.DB_PORT_TEST }}/postgres" >> $GITHUB_ENV

    - name: Run tests
      run: |
        export DATABASE_URL="postgres://${{ secrets.DB_USER_TEST }}:${{ secrets.DB_PASS_TEST }}@${{ secrets.DB_HOST_TEST }}:${{ secrets.DB_PORT_TEST }}/postgres"
        pytest
